### ISSUE TITLE
create entity for posts module

### ISSUE THREAD

**Issue by sru-thy** [TnP-MACE/macebook-backend#2]

**Comment by ahammed3216** [comment]
import {Entity,PrimaryGeneratedColumn,ManyToOne,JoinColumn, Column} from 'typeorm';
import  User from 'src/user/entities/user.entity';
import { GenericEntity } from 'src/generic/generic.entity';

@Entity({ name: 'posts'})
export class PostEntity extends GenericEntity{
    @PrimaryGeneratedColumn()
    id:number;

    @Column({length:50})
    title:string;

    @Column('text')
    body:string;

    @ManyToOne( () => User,(user:User) => user.posts,{onUpdate:'CASCADE',onDelete:'CASCADE'} )
    @JoinColumn({ name :'user_id' })
    user:User;
}
